export const networkKeys = [
  "cosmos",
  "polkadot",
  "kava",
  "terra-money",
  "iris",
  // "desmos",
  "likecoin",
  // "cyberd",
  "e-money",
  "regen-network",
  "band-protocol",
  "akash",
  "iov",
  "kusama",
  "sentinel",
  "oasis-protocol",
  "bitsongs",
  "solana",
  "celo",
  "agoric",
  "flow",
  "persistence-one",
  "sharering",
  "fetch.ai",
  "injective-protocol",
  "straightedge",
  "oasis-labs",
].sort();
