/* eslint-disable no-useless-computed-key */
/* eslint-disable no-unused-vars */
/* eslint-disable no-use-before-define */
import * as R from 'ramda';

interface IStringIndex extends Record<string, any> {}

/**
 * Takes the key name and returns the location. Will return null if undefined
 */

const logos: IStringIndex = {
  cosmos: {
    image: '/images/network/cosmos_hub.png',
    name: 'Cosmos Hub',
    label: 'Cosmos Hub - ATOM',
    key: 'cosmos',
    graphql: 'cosmos',
    value: 'cosmos',
    denom: 'ATOM',
    color: '#ba3fd9',
    bigDipper: 'https://cosmos.bigdipper.live/',
    delegate:
      'https://cosmos.bigdipper.live/validators/cosmosvaloper14kn0kk33szpwus9nh8n87fjel8djx0y070ymmj/delegate',
    heightSocket: 'wss://ws.cosmoshub.forbole.com',
    guide: 'how-to-stake-atom-on-cosmos-hub',
    calculator: {
      bonded: 'http://lcd.cosmoshub.bigdipper.live/staking/pool',
      inflation: 'http://lcd.cosmoshub.bigdipper.live/minting/inflation',
      supply: 'http://lcd.cosmoshub.bigdipper.live/supply/total/uatom',
      stakingParams:
        'http://lcd.cosmoshub.bigdipper.live/staking/validators/cosmosvaloper14kn0kk33szpwus9nh8n87fjel8djx0y070ymmj',
    },
  },
  agoric: {
    image: '/images/network/agoric.png',
    name: 'Agoric',
    denom: 'bld',
    key: 'agoric',
    graphql: 'agoric',
    delegate:
      'https://wallet.keplr.app/#/agoric/stake?tab=inactive-validators&modal=detail&validator=agoricvaloper1pcc069wu2utgnf5qsm6n2pk2x8xt6cah954t4g',
    bigDipper: 'https://testnet.explorer.agoric.net/',
    guide: 'how-to-stake-bld-on-agoric',
  },
  akash: {
    image: '/images/network/akash.png',
    name: 'Akash',
    label: 'Akash - AKT',
    key: 'akash',
    graphql: 'akash',
    denom: 'AKT',
    color: '#eb3825',
    bigDipper: 'https://akash.bigdipper.live/',
    delegate:
      'https://akash.bigdipper.live/validator/akashvaloper14kn0kk33szpwus9nh8n87fjel8djx0y0uzn073/delegate',
    heightSocket: 'wss://ws.akash.forbole.com',
    guide: 'how-to-stake-akt-on-akash',
    calculator: {
      bonded: 'https://api.akash.forbole.com/staking/pool',
      inflation: 'https://api.akash.forbole.com/minting/inflation',
      supply: 'https://api.akash.forbole.com/bank/total/uakt',
      stakingParams:
        'https://api.akash.forbole.com/staking/validators/akashvaloper14kn0kk33szpwus9nh8n87fjel8djx0y0uzn073',
    },
  },
  ['band-protocol']: {
    image: '/images/network/band_protocol.png',
    name: 'Band Protocol',
    label: 'Band Protocol - BAND',
    key: 'band-protocol',
    graphql: 'band',
    denom: 'BAND',
    color: '#516FFA',
    heightSocket: 'wss://ws.band.forbole.com',
    bigDipper: 'https://band.bigdipper.live/',
    delegate: 'https://atomicwallet.io/band-staking',
    calculator: {
      bonded: 'http://lcd.band.forbole.com/staking/pool',
      inflation: 'http://lcd.band.forbole.com/minting/inflation',
      supply: 'http://lcd.band.forbole.com/supply/total/uband',
      stakingParams:
        'http://lcd.band.forbole.com/staking/validators/bandvaloper14kn0kk33szpwus9nh8n87fjel8djx0y0wz502z',
    },
  },
  bitsong: {
    image: '/images/network/bitsong.png',
    name: 'BitSong',
    denom: 'btsg',
    key: 'bitsong',
    graphql: 'bitsong',
    delegate: 'https://wallet.bitsong.io/#/authentication/login',
    guide: 'how-to-stake-btsg-on-bitsong',
  },
  'crypto.org': {
    image: '/images/network/crypto_org.png',
    name: 'Cronos',
    label: 'Cronos - CRO',
    denom: 'cro',
    key: 'crypto-org',
    graphql: 'cro',
    delegate:
      'https://crypto-org.bigdipper.live/validator/crocncl15xphw2m025acwnjd2ucq9t5ku4ggaqyecekzqa',
    bigDipper: 'https://crypto-org.bigdipper.live/',
  },
  desmos: {
    image: '/images/network/desmos.png',
    name: 'Desmos',
    denom: 'dsm',
    key: 'desmos',
    graphql: 'desmos',
    bigDipper: 'https://morpheus.desmos.network/',
  },
  ['e-money']: {
    image: '/images/network/e_money.png',
    name: 'eMoney',
    denom: 'ngm',
    key: 'e-money',
    graphql: 'emoney',
    color: '#1e5877',
    bigDipper: 'https://e-money.network/',
    delegate:
      'https://wallet.e-money.com/earn/emoneyvaloper1293pqwtzu67zp8txuya4yts03ccw5kgf98hz9y',
    heightSocket: 'wss://ws.emoney.forbole.com',
    guide: 'how-to-stake-ngm-on-e-money',
    calculator: {
      bonded: 'http://lcd.emoney.forbole.com/staking/pool',
      inflation: 'http://lcd.emoney.forbole.com/minting/inflation',
      supply: 'http://lcd.emoney.forbole.com/supply/total/nanolike',
      stakingParams:
        'http://lcd.emoney.forbole.com/staking/validators/emoneyvaloper1293pqwtzu67zp8txuya4yts03ccw5kgf98hz9y',
    },
  },
  evmos: {
    image: '/images/network/evmos.png',
    name: 'Evmos',
    label: 'Evmos - EVMOS',
    denom: 'evmos',
    key: 'evmos',
    graphql: 'evmos',
    delegate: 'https://app.evmos.org/staking',
  },
  ['fetch-ai']: {
    image: '/images/network/fetch_ai.png',
    name: 'Fetch.ai',
    label: 'Fetch.ai - FET',
    denom: 'fet',
    key: 'fetch-ai',
    graphql: 'fetchai',
    delegate:
      'https://explore.fetch.ai/validator/fetchvaloper14kn0kk33szpwus9nh8n87fjel8djx0y0dzxfx3',
    bigDipper: 'https://explore.fetch.ai/',
  },
  comdex: {
    image: '/images/network/comdex.png',
    name: 'Comdex',
    label: 'Comdex - CMDX',
    denom: 'cmdx',
    key: 'comdex',
    graphql: 'comdex',
    address: 'comdexvaloper1e4wjh48ks5j5d9702d35q360ffmf3jj2xpuf3f',
    guide: 'how-to-stake-cmdx-on-comdex',
    delegate: 'https://comdex.omniflix.co/',
  },
  axelar: {
    image: '/images/network/axelar.png',
    name: 'Axelar',
    label: 'Axelar - AXL',
    denom: 'axl',
    key: 'axelar',
    graphql: 'axelar',
    guide: 'how-to-stake-axl-on-axelar',
    delegate: 'https://wallet.keplr.app/chains/axelar',
  },
  bitcanna: {
    image: '/images/network/bitcanna.png',
    name: 'Bitcanna',
    label: 'BitCanna - BCNA',
    denom: 'bcna',
    key: 'bitcanna',
    graphql: 'bitcanna',
    guide: 'how-to-stake-bcna-on-bitcanna',
    delegate: 'https://wallet.bitcanna.io/',
  },
  // bifrost: {
  //   guide: 'how-to-stake-bnc-on-bifrost',
  // },
  cheqd: {
    image: '/images/network/cheqd.png',
    name: 'Cheqd',
    label: 'CHEQD Network - CHEQ',
    denom: 'cheq',
    key: 'cheqd',
    graphql: 'cheqd',
    guide: 'how-to-stake-cheq-on-cheqd',
    delegate: 'https://wallet.cheqd.io',
  },
  chihuahua: {
    image: '/images/network/chihuahua.png',
    name: 'Chihuahua',
    label: 'Chihuahua Chain - HUAHUA',
    denom: 'huahua',
    key: 'chihuahua',
    graphql: 'chihuahua',
    guide: 'how-to-stake-huahua-on-chihuahua',
    delegate: 'https://chihuahua.omniflix.co/',
  },
  ['terra_classic']: {
    image: '/images/network/terra_classic.png',
    name: 'Terra Classic',
    label: 'Terra Classic - LUNC',
    denom: 'LUNC',
    key: 'terra_classic',
    graphql: 'terra_classic',
  },
  persistence: {
    image: '/images/network/persistence.png',
    name: 'Persistence',
    label: 'Persistence - XPRT',
    denom: 'xprt',
    key: 'persistence',
    graphql: 'persistence',
    guide: 'how-to-stake-xprt-on-persistence',
    delegate: 'https://wallet.keplr.app/chains/persistence',
  },
  crescent: {
    image: '/images/network/crescent.png',
    name: 'Crescent',
    label: 'Crescent Network - CRE',
    denom: 'cre',
    key: 'crescent',
    graphql: 'crescent',
    guide: 'how-to-stake-cre-on-crescent',
    delegate: 'https://crescent.disperze.network/',
  },
  ixo: {
    image: '/images/network/ixo.png',
    name: 'ixo',
    label: 'IXO - IXO',
    denom: 'ixo',
    key: 'ixo',
    graphql: 'ixo',
    guide: 'how-to-stake-ixo-on-ixo',
    delegate: 'https://wallet.keplr.app/chains/ixo',
  },
  injective: {
    image: '/images/network/injective.png',
    name: 'Injective',
    label: 'Injective - INJ',
    denom: 'inj',
    key: 'injective',
    graphql: 'injective',
  },
  juno: {
    image: '/images/network/juno.png',
    name: 'Juno',
    label: 'Juno - JUNO',
    denom: 'juno',
    key: 'juno',
    graphql: 'juno',
  },
  kava: {
    image: '/images/network/kava.png',
    name: 'Kava',
    label: 'Kava - KAVA',
    denom: 'kava',
    key: 'kava',
    graphql: 'kava',
    guide: 'how-to-stake-kava-on-kava',
    delegate: 'https://wallet.keplr.app/chains/kava',
  },
  band: {
    image: '/images/network/band_protocol.png',
    name: 'Band',
    denom: 'band',
    label: 'Band Protocol - BAND',
    key: 'band',
    graphql: 'band',
  },
  likecoin: {
    image: '/images/network/likecoin.png',
    name: 'Likecoin',
    label: 'Likecoin - LIKE',
    denom: 'like',
    key: 'likecoin',
    graphql: 'likecoin',
    guide: 'how-to-stake-like-on-likecoin',
    delegate: 'https://dao.like.co/',
  },
  assetmantle: {
    image: '/images/network/assetmantle.png',
    name: 'Assetmantle',
    label: 'Assetmantle - MNTL',
    denom: 'mntl',
    key: 'assetmantle',
    graphql: 'assetmantle',
    guide: 'how-to-stake-mntl-on-assetmantle',
    delegate: 'https://wallet.assetmantle.one/',
  },
  osmosis: {
    image: '/images/network/osmosis.png',
    name: 'Osmosis',
    label: 'Osmosis - OSMO',
    denom: 'osmo',
    key: 'osmosis',
    graphql: 'osmosis',
    guide: 'how-to-stake-osmo-on-osmosis',
    delegate: 'https://wallet.keplr.app/chains/osmosis',
  },
  provenance: {
    image: '/images/network/provenance.png',
    name: 'Provenance',
    denom: 'hash',
    key: 'provenance',
    graphql: 'provenance',
  },
  regen: {
    image: '/images/network/regen.png',
    name: 'Regen',
    label: 'Regen - REGEN',
    denom: 'regen',
    key: 'regen',
    graphql: 'regen',
  },
  secret: {
    image: '/images/network/secret.png',
    name: 'Secret',
    label: 'Secret - SCRT',
    denom: 'scrt',
    key: 'secret',
    graphql: 'secret',
    guide: 'how-to-stake-scrt-on-secret-network',
    delegate: 'https://wallet.keplr.app/chains/secret-network',
  },
  sentinel: {
    image: '/images/network/sentinel.png',
    name: 'Sentinel',
    label: 'Sentinel - DVPN',
    denom: 'dvpn',
    key: 'sentinelhub',
    graphql: 'sentinelhub',
    guide: 'how-to-stake-dvpn-on-sentinel',
    delegate: 'https://wallet.keplr.app/chains/sentinel',
  },
  shentu: {
    image: '/images/network/shentu.png',
    name: 'Shentu',
    label: 'Shentu - CTK',
    denom: 'ctk',
    key: 'shentu',
    graphql: 'shentu',
  },
  sifchain: {
    image: '/images/network/sifchain.png',
    name: 'Sifchain',
    label: 'Sifchain - EROWAN',
    denom: 'erowan',
    key: 'sifchain',
    graphql: 'sifchain',
    guide: 'how-to-stake-rowan-on-sifchain',
    delegate: 'https://wallet.keplr.app/chains/sifchain',
  },
  sommelier: {
    image: '/images/network/sommelier.png',
    name: 'Sommelier',
    label: 'Sommelier - SOMM',
    denom: 'somm',
    key: 'sommelier',
    graphql: 'sommelier',
  },
  stafihub: {
    image: '/images/network/stafihub.png',
    name: 'Stafihub',
    label: 'Stafi - FIS',
    denom: 'fis',
    key: 'stafihub',
    graphql: 'stafihub',
  },
  stride: {
    image: '/images/network/stride.png',
    name: 'Stride',
    label: 'Stride - STRD',
    denom: 'strd',
    key: 'stride',
    graphql: 'stride',
  },
  elrond: {
    image: '/images/network/elrond.png',
    name: 'Elrond',
    denom: 'egld',
    key: 'elrond',
    graphql: 'elrond',
  },
  // ['gravity-bridge']: {
  //   guide: 'how-to-stake-grav-on-gravity-bridge',
  // },
  // nomic: {
  //   guide: 'how-to-stake-nom-on-nomic',
  // },
};

export const getNetworkInfo = (key: string | number) => {
  return logos[key] ?? {};
};
