export const calculatorKeys = [
  'cosmos',
  'fetch-ai',
  'crypto.org',
  'evmos',
  'comdex',
  'axelar',
  'bitcanna',
  'cheqd',
  'chihuahua',
  'terra_classic',
  'persistence',
  'crescent',
  'ixo',
  'injective',
  'juno',
  'kava',
  'band',
  'likecoin',
  'assetmantle',
  'osmosis',
  'regen',
  'secret',
  'sentinel',
  'shentu',
  'sifchain',
  'stafihub',
  'stride',
  // coingecko not updating its market price:
  // 'provenance',
  // awaiting for back-end data:
  // 'sommelier',
  'gravity_bridge',
  'jackal',
].sort();
